package com.cumt.criminal.model;
// default package
// Generated 2016-4-29 22:46:04 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Arrest generated by hbm2java
 */
public class ArrestDomain implements java.io.Serializable {

	private Integer id;
	private int caseRegisterId;
	private String chargeName;
	private String reason;
	private boolean state;
	private boolean resultState;
	private Date time;
	private String handleName;
/*private CaseRegisterDomain caseRegisterDomain;

	public CaseRegisterDomain getCaseRegisterDomain() {
	return caseRegisterDomain;
}

public void setCaseRegisterDomain(CaseRegisterDomain caseRegisterDomain) {
	this.caseRegisterDomain = caseRegisterDomain;
}*/
	public ArrestDomain() {
	}

	public ArrestDomain(int caseRegisterId, String chargeName, String reason,
			boolean state, boolean resultState, Date time, String handleName) {
		this.caseRegisterId = caseRegisterId;
		this.chargeName = chargeName;
		this.reason = reason;
		this.state = state;
		this.resultState = resultState;
		this.time = time;
		this.handleName = handleName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getCaseRegisterId() {
		return this.caseRegisterId;
	}

	public void setCaseRegisterId(int caseRegisterId) {
		this.caseRegisterId = caseRegisterId;
	}

	public String getChargeName() {
		return this.chargeName;
	}

	public void setChargeName(String chargeName) {
		this.chargeName = chargeName;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public boolean isState() {
		return this.state;
	}

	public void setState(boolean state) {
		this.state = state;
	}

	public boolean isResultState() {
		return this.resultState;
	}

	public void setResultState(boolean resultState) {
		this.resultState = resultState;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getHandleName() {
		return this.handleName;
	}

	public void setHandleName(String handleName) {
		this.handleName = handleName;
	}

}
