package com.cumt.criminal.model;
// default package
// Generated 2016-4-29 20:43:14 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Detention generated by hbm2java
 */
public class DetentionDomain implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private int caseRegisterId;
	private String chargeName;
	private String reason;
	private boolean state;
	private boolean resultState;
	private String handleName;
	private Date time;

	public DetentionDomain() {
	}

	public DetentionDomain(int caseRegisterId, String chargeName,String reason, boolean state,
			boolean resultState, String handleName, Date time) {
		this.caseRegisterId = caseRegisterId;
		this.chargeName = chargeName;
		this.reason = reason;
		this.state = state;
		this.resultState = resultState;
		this.handleName = handleName;
		this.time = time;
	}

	public String getChargeName() {
		return chargeName;
	}

	public void setChargeName(String chargeName) {
		this.chargeName = chargeName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getCaseRegisterId() {
		return this.caseRegisterId;
	}

	public void setCaseRegisterId(int caseRegisterId) {
		this.caseRegisterId = caseRegisterId;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public boolean isState() {
		return this.state;
	}

	public void setState(boolean state) {
		this.state = state;
	}

	public boolean isResultState() {
		return this.resultState;
	}

	public void setResultState(boolean resultState) {
		this.resultState = resultState;
	}

	public String getHandleName() {
		return this.handleName;
	}

	public void setHandleName(String handleName) {
		this.handleName = handleName;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}
